services:
  postgres:
    container_name: ms_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "@Kalilinux3"
      POSTGRES_USER: cpulsivek
      POSTGRES_MULTIPLE_DATABASES: UserDB,VideoDB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - microservice-net

  kafka:
    image: landoop/fast-data-dev:latest
    container_name: ms_kafka
    ports:
      - 3181:3181
      - 3040:3040
      - 7082:7082
      - 7083:7083
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      SAMPLEDATA: 0
      BROKER_PORT: 9092
      REST_PORT: 7082
      CONNECT_PORT: 7083
      ZK_PORT: 3181
      WEB_PORT: 3040
      REGISTRY_PORT: 8081
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: ms_zipkin
    ports:
      - 9490:9411
    networks:
      - microservice-net

  prometheus:
    image: prom/prometheus:latest
    container_name: ms_prometheus
    restart: unless-stopped
    ports:
      - '9491:9090'
    volumes:
      - ./data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    image: grafana/grafana:latest
    container_name: ms_grafana
    restart: unless-stopped
    ports:
      - '9492:3000'
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana/config:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOWS_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file

volumes:
  postgres:
  mongo:
  pgadmin:

networks:
  microservice-net: