spring.application.name=gateway
server.port=${PORT}
# Eureka client registration disabled
eureka.client.register-with-Eureka=false
# Enable discovery locator for routes
spring.cloud.gateway.mvc.discovery.locator.enabled=true
spring.cloud.gateway.mvc.discovery.locator.lowerCaseServiceId=true
# Gateway routes
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=${USER_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/user/**
spring.cloud.gateway.mvc.routes[1].id=upload-service
spring.cloud.gateway.mvc.routes[1].uri=${UPLOAD_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/upload/**
spring.cloud.gateway.mvc.routes[2].id=notification-service
spring.cloud.gateway.mvc.routes[2].uri=${NOTIFICATION_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/notification/**
spring.cloud.gateway.mvc.routes[3].id=discovery
spring.cloud.gateway.mvc.routes[3].uri=${DISCOVERY_ORIGIN}
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.mvc.routes[3].filters=SetPath=/
spring.cloud.gateway.mvc.routes[4].id=discovery-static
spring.cloud.gateway.mvc.routes[4].uri=${DISCOVERY_ORIGIN}
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/eureka/**
# Documentation routes
spring.cloud.gateway.mvc.routes[5].id=user_service_api_docs
spring.cloud.gateway.mvc.routes[5].uri=${USER_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/${USER_SERVICE_ORIGIN}/v3/api-docs
spring.cloud.gateway.mvc.routes[5].predicates[1]=Method=GET
spring.cloud.gateway.mvc.routes[6].id=upload_service_api_docs
spring.cloud.gateway.mvc.routes[6].uri=${UPLOAD_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/${UPLOAD_SERVICE_ORIGIN}/v3/api-docs
spring.cloud.gateway.mvc.routes[6].predicates[1]=Method=GET
spring.cloud.gateway.mvc.routes[7].id=account_management_api_docs
spring.cloud.gateway.mvc.routes[7].uri=${NOTIFICATION_SERVICE_ORIGIN}
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/${NOTIFICATION_SERVICE_ORIGIN}/v3/api-docs
spring.cloud.gateway.mvc.routes[7].predicates[1]=Method=GET
# spring doc config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.urls[0].url=/${USER_SERVICE_ORIGIN}/v3/api-docs
springdoc.swagger-ui.urls[0].name=USER SERVICE
springdoc.swagger-ui.urls[1].url=/${UPLOAD_SERVICE_ORIGIN}/v3/api-docs
springdoc.swagger-ui.urls[1].name=UPLOAD SERVICE
springdoc.swagger-ui.urls[2].url=/${NOTIFICATION_SERVICE_ORIGIN}/v3/api-docs
springdoc.swagger-ui.urls[2].name=NOTIFICATION SERVICE
# Zipkin Tracing Configuration
management.zipkin.tracing.endpoint=${ZIPKIN_TRACING_ENDPOINT}
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=ALWAYS
management.tracing.sampling.probability=1.0
# CORS
spring.cloud.gateway.default-filters=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=${FRONTEND_ORIGIN}
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,DELETE,PUT,OPTIONS




