spring.application.name=upload-service
server.port=${PORT}

# eureka config
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_DEFAULT_ZONE}

# spring config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring doc config
springdoc.api-docs.path=/${SERVICE_ORIGIN}/v3/api-docs
springdoc.swagger-ui.path=/${SERVICE_ORIGIN}/swagger-ui.html

# Zipkin Tracing Configuration
management.zipkin.tracing.endpoint=${ZIPKIN_TRACING_ENDPOINT}
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=ALWAYS
management.tracing.sampling.probability=1.0

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# jwt
jwt_secret=${JWT_SECRET}

# aws
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.bucket.name=${AWS_BUCKET_NAME}

# origin
user.service.origin=${USER_SERVICE_ORIGIN}
notification.service.origin=${NOTIFICATION_SERVICE_ORIGIN}

logging.level.org.springframework.security=TRACE
