spring.application.name=user-service
server.port=${PORT}

# eureka config
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_DEFAULT_ZONE}

# spring config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring doc config
springdoc.api-docs.path=/${SERVICE_ORIGIN}/v3/api-docs
springdoc.swagger-ui.path=/${SERVICE_ORIGIN}/swagger-ui.html


# Zipkin Tracing config
management.zipkin.tracing.endpoint=${ZIPKIN_TRACING_ENDPOINT}
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=ALWAYS
management.tracing.sampling.probability=1.0

# jwtService
jwt_secret=${JWT_SECRET}

# origins
upload.service.origin=${UPLOAD_SERVICE_ORIGIN}